In [1]:
#Import dependencies
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size =.3)

In [6]:
len(X_train)

105

In [7]:
len(X_test)

45

In [8]:
import warnings as wn
wn.filterwarnings('ignore')

In [9]:
#Train RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9333333333333333

In [10]:
#Train Logistic Regression Classifier
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9555555555555556

In [11]:
#Train SVM
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9777777777777777

In [16]:
#Train Decison Tree Classifier
from sklearn.tree import DecisionTreeClassifier

In [17]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
dt.score(X_test, y_test)

0.9333333333333333

In [12]:
from sklearn.model_selection import cross_val_score

In [19]:
rf_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rf_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [20]:
lr_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
lr_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [21]:
svm_scores = cross_val_score(SVC(), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [22]:
dt_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dt_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [24]:
np.average(rf_scores)

0.96

In [25]:
np.average(lr_scores)

0.9733333333333334

In [27]:
np.average(svm_scores)

0.9666666666666666

In [28]:
np.average(dt_scores)

0.9666666666666668

###### Logistic Regression has the highest score: 0.973333